### ISSUE TITLE
Could you remove wodby email from travisci build notifications?

### ISSUE THREAD

**Issue by pprishchepa** [ahernandezsouza/aws-translate-test#1]
Hi there, could anybody remove wodby email from the notification section in `.travis.yml`?
```
notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
```
